version: '3.4'
services:
  docker-mysql:
    image: mariadb
    container_name: docker-mysql
    ports:
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: hongjiahuang
    volumes:
      - $HOME/docker-data/mysql/data:/var/lib/mysql # mysql数据目录
    restart: always
  docker-php:
    build: ./php
#    image: docker-php
    container_name: docker-php
    links:
      - docker-mysql:docker-mysql
    depends_on:
      - docker-mysql
    ports:
      - 9000:9000
    volumes:
      - $HOME/docker-data/www:/docker-data/www # php代码目录
    restart: always
  docker-nginx:
    image: nginx
    container_name: docker-nginx
    ports:
      - 80:80
    volumes:
      - $HOME/docker-data/www:/docker-data/www # 项目目录
      - $HOME/docker-data/nginx/conf.d:/etc/nginx/conf.d # nginx配置文件目录
      - $HOME/docker-data/nginx/log:/var/log/nginx # nginx日志目录
    depends_on:
      - docker-php
    links:
      - docker-php:docker-php
    restart: always
